import jsPDF from "jspdf";

export const generateReport = (doc) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();

  // Header
  pdf.setFillColor(37, 99, 235);
  pdf.rect(0, 0, pageWidth, 40, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(22);
  pdf.setFont("helvetica", "bold");
  pdf.text("Legal Analyzer Report", 20, 25);

  // File name
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.text(`File: ${doc.fileName}`, 20, 35);

  // Date
  pdf.text(`Generated: ${new Date().toLocaleDateString("en-IN")}`, pageWidth - 60, 35);

  // Risk Score Box
  pdf.setTextColor(0, 0, 0);
  pdf.setFillColor(
    doc.riskLevel === "High" ? 254 : doc.riskLevel === "Medium" ? 254 : 240,
    doc.riskLevel === "High" ? 226 : doc.riskLevel === "Medium" ? 243 : 253,
    doc.riskLevel === "High" ? 226 : doc.riskLevel === "Medium" ? 200 : 244
  );
  pdf.rect(15, 50, pageWidth - 30, 35, "F");
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text(`Risk Score: ${doc.riskScore}/10`, 20, 65);
  pdf.text(`Risk Level: ${doc.riskLevel}`, 20, 78);

  // Summary
  pdf.setFontSize(13);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(37, 99, 235);
  pdf.text("Document Summary", 20, 100);
  pdf.setTextColor(0, 0, 0);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  const summaryLines = pdf.splitTextToSize(doc.summary || "N/A", pageWidth - 40);
  pdf.text(summaryLines, 20, 112);

  let y = 112 + summaryLines.length * 6 + 10;

  // Key Points
  if (doc.keyPoints && doc.keyPoints.length > 0) {
    pdf.setFontSize(13);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(37, 99, 235);
    pdf.text("Key Points", 20, y);
    y += 10;
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);
    doc.keyPoints.forEach((point) => {
      pdf.text(`• ${point}`, 25, y);
      y += 8;
    });
    y += 5;
  }

  // Risky Clauses
  if (doc.riskyClauses && doc.riskyClauses.length > 0) {
    if (y > 240) { pdf.addPage(); y = 20; }
    pdf.setFontSize(13);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(37, 99, 235);
    pdf.text("Risky Clauses", 20, y);
    y += 10;

    doc.riskyClauses.forEach((clause, i) => {
      if (y > 260) { pdf.addPage(); y = 20; }
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(10);
      pdf.setTextColor(
        clause.risk === "high" ? 220 : clause.risk === "medium" ? 180 : 22,
        clause.risk === "high" ? 38 : clause.risk === "medium" ? 120 : 163,
        clause.risk === "high" ? 38 : clause.risk === "medium" ? 0 : 74
      );
      pdf.text(`[${clause.risk?.toUpperCase()} RISK] ${clause.text}`, 20, y);
      y += 7;
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(80, 80, 80);
      const expLines = pdf.splitTextToSize(clause.explanation || "", pageWidth - 45);
      pdf.text(expLines, 25, y);
      y += expLines.length * 6 + 6;
    });
  }

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text("Generated by Legal Analyzer — AI-Powered Contract Intelligence", 20, 285);

  pdf.save(`${doc.fileName}-analysis.pdf`);
};